amazonProperties:
  endpointUrl: s3.eu-north-1.amazonaws.com
  accessKey: "your accessKey"
  secretKey: "your secretKey"
  bucketName: "your bucketName"

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port=8091:

